name: Build for Linux

on:
  push:
    tags:
      - "v*.*.*"


env:
  GH_TOKEN:
    ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn build --linux
    - run: rm -rf ./dist/*.yml ./dist/*.yaml ./dist/linux-unpacked
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload multiple assets to release
      uses: csexton/release-asset-action@v3
      with:
        pattern: "dist/*"
        github-token: ${{ secrets.GH_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
